name: Build and Publish Packages

on:
  release:
    types: [created]
  push:
    branches:
      - dev/nodejs-support
  workflow_dispatch:
    inputs:
      version:
        description: "Version for Manual Release (e.g., 1.2.3-beta)"
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Determine Version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/dev/nodejs-support" ]; then
            echo "VERSION=0.0.0-test" >> $GITHUB_ENV
          fi

      - name: Build NPM Package
        run: |
          echo "Building Version ${{ env.VERSION }}"
          deno run -A scripts/build-npm.ts ${{ env.VERSION }}

      - name: Publish to NPM
        run: |
          cd npm
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Published Package for Testing
        run: npm install -g @stackql/stackqljs@${{ env.VERSION }}

      - name: Run Integration Test
        run: stackql exec "SHOW PROVIDERS"
