name: Build and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Build NPM Package
        run: deno run -A scripts/npm-build.ts ${{ github.event.ref }}

      - name: Publish to NPM
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Deno
        run: |
          # Add the commands to publish to Deno
          # This might involve updating a Deno module registry
          # or pushing the module to a specific GitHub repository
