name: Build and Publish Packages

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional Tag (e.g., beta, release-v1.2) - Leave empty for standard release"
        required: false
        default: ""

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"

      - name: Determine Tag
        id: get_tag
        run: |
          echo "TAG=${{ github.event.inputs.tag || github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build NPM Package
        run: deno run -A scripts/npm-build.ts ${{ env.TAG }}

      # Additional steps specific to your build and test process

      - name: Publish to NPM
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        run: |
          cd npm
          npm publish --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Additional steps for Deno publication, if any
